### ISSUE TITLE
Simulation errors: divide by zero, etc.

### ISSUE THREAD

**Issue by jeremylhour** [jlhourENSAE/CIC-asymptotics#4]
/Users/jeremylhour/Documents/code/CIC-asymptotics/functions/func_main.py:97: RuntimeWarning: divide by zero encountered in true_divide
  inside_integral = (indicator-u_hat)/denominateur

**Comment by jlhourENSAE** [comment]
Sample size: 10,000

Theta_0: 2.22
Number of simulations: 1000 

bias: 
- smoothed: 0.0001
- standard: 0.0002


MAE: 
- smoothed: 0.0037
- standard: 0.0038


RMSE: 
- smoothed: 0.0047
- standard: 0.0047


Coverage rate: 
**- smoothed: 0.8960**
- standard: 0.9490

**Comment by jeremylhour** [comment]
manage using a try/except, can cause trouble (gives estimator = inf)
